# Postgres

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: sonica-api_development
  username: stefanie

test:
  <<: *default
  database: sonica-api_test
  username: stefanie

production:
  <<: *default
  database: sonica-api_production
  username: deploy
